### PR TITLE
Feature/justins logo and 2 Bug Fixes for Businesses Card Styling

### PR DESCRIPTION
**Pull request by juanri0s**
# Describe your PR

- Added Justin's logo to About section under his name and linked to https://www.ThugDebugger.dev'
- Fixes business card description/location having wrong style
- Fixes business card description not showing elipses (this happened because substring returns a new string so checking if it's greater than the max did nothing because they were equal! So switched to checking if they matched and showing them

Related to #
Fixes #

### Screenshots / video of changes

Drop some screenshots of the before and after of your work here. Better yet, take a screen recording using a tool like [Loom](https://www.loom.com/)

image

Businesses styling bug fixes:
image

## Steps to test

1. Go to /about
2. inspect logo under Justin's name

1. Go to /businesses
2. Find a business with description
3. Check the styling
4. Find a business with a long description (> 250 char)
4. Check that it has elipses

### CODE REVIEW

**Comment by juanri0s** [comment]
[Business result card: Add ellipses after text max char cutoff](https://trello.com/c/3yTBEoEl/175-business-result-card-add-ellipses-after-text-max-char-cutoff)

**Comment by juanri0s** [comment]
[Business result card: wrong font](https://trello.com/c/SCloUG0z/176-business-result-card-wrong-font)

**Comment by racedale** [comment]
At a medium screen size the logo goes left aligned
Screen Shot 2020-06-11 at 9 54 23 PM

**Comment by juanri0s** [comment]
> At a medium screen size the logo goes left aligned
> Screen Shot 2020-06-11 at 9 54 23 PM

fixed!

**Pull request merged**
