### PR TITLE
Move from navigate to window.locate for search filters

### PR DESCRIPTION
**Pull request by llexical**
Navigate in Gatsby was causing a full rerender of the page on trigger,
which meant that n1, you were pushed to the top of the page quite
violently every time you did a search but also with a search being
programatically triggered, it would then get retriggered by the page
refresh. There would then be a race condition and everything got a bit
strange.

One way to solve this would have been to stuck with just using page
refreshes however I much prefer a dynamic search without jumping around
all over the place so went in that direction.

I have stored a page location object which I updated with the new path
name and search params when filters change the URL which allows it to
act like navigate for the pagination which uses page location. I could
have setup pagination to then change page dynamically as well but then
you need to scroll to things and page refreshing is an easy way to skip
all that. Also means the pagination would not have been as easily
reusable.

Its a bit of a Frakensteins monster, however I hope it makes sense!
Happy for any review comments/ideas.

# Describe your PR

Related to #
Fixes #

### Screenshots / video of changes

Drop some screenshots of the before and after of your work here. Better yet, take a screen recording using a tool like [Loom](https://www.loom.com/)

## Steps to test

1.

### CODE REVIEW

**Comment by llexical** [comment]
Forgot to say, much credit to: https://github.com/Rebuild-Black-Business/RBB-Website/pull/246 who figured out what was going on!

**Comment by mbifulco** [comment]
@llexical how can I test this out?

**Comment by racedale** [comment]
@mbifulco Here's the trello card with details
https://trello.com/c/QNWA1y7N/205-when-changing-search-type-to-all-from-in-need-with-predefined-search-parameters-it-just-returns-all-results

**Comment by llexical** [comment]
@mbifulco Heres a link: https://5ee38e9165cec40007cd3574--rebuild-black-business.netlify.app/

**Pull request merged**
