### PR TITLE
add cypress ci github action

### PR DESCRIPTION
**Pull request by jamiebuilds**
# Describe your PR

Adding cypress integration tests to CI on pull requests

## Pages/Interfaces that will change

None

## Steps to test

1. Might have to create a new PR to see if it actually runs

### Additional notes

(Gonna see if it just works on this PR, I've never tried this on GitHub PRs before)

### CODE REVIEW

**Comment by racedale** [comment]
This is the issue we ran into for context
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

https://discordapp.com/channels/717124695979458570/717197846297706529/718544669851648002

**Comment by racedale** [comment]
There's also probably a few secrets that need added/updated. I just updated the `AIRTABLE_API_KEY` and added another for `AIRTABLE_BASE_ID`. Not sure how many are actually needed to get Cypress connected

**Comment by jamiebuilds** [comment]
@racedale Okay, how about I try this in two stages then. Right now it ran a couple of the tests just fine. But the a11y test needs the airtable token. I can omit that test from CI for now and work on that in a separate PR

**Comment by jamiebuilds** [comment]
Oh lol, missed a lot of the test results, I thought only one of them failed. Will dig more

**Comment by racedale** [comment]
It looks like the `API key is required to connect to Airtable` comes just from Gatsby trying to start up. I recommend starting on just the `navigation` tests, those should be able to be passing

**Comment by jamiebuilds** [comment]
Hm, it kinda sounds like this repo actually need a merge queue like https://bors.tech/ which can run CI actions prior to merge. By having you approve a pull request before it runs privileged CI processes, you can protect your secrets and ensure that everything you are merging is safe.

I can help you set that up if you'd like, but we should probably do it over a video call.

**Comment by jamiebuilds** [comment]
I don't actually have it setup in a repo right now but this is vaguely what it looks like:

Screen Shot 2020-06-11 at 10 18 57 PM


Screen Shot 2020-06-11 at 10 19 02 PM

**Comment by racedale** [comment]
Before setting up Bors I first setup Circle CI to run the builds in #257 . I has the ability to provide secrets to forked PR's unlike GitHub actions so it's working for now. May look into adding Bors in the future though!

**Pull request closed without merging**
