### PR TITLE
Feature/update link styles across the site

### LINKED ISSUE #314: [Feature] Update link styles across the site
## User Story
As a user
I want to see consistent link styles across the site

## Acceptance Criteria
- [ ] Ensure all link styles throughout the site match the brand guidelines defined here: https://www.figma.com/file/Lo1ZcBOO9t4QRbX2I0PwBQ/RBB?node-id=2022%3A4381

## Describe the solution you'd like
We need to make sure that all text link styles match the designs outlined above, for both light and dark background colors.

### PR DESCRIPTION
**Pull request by AdrianTNare**
# Describe your PR
This updates the link styles across the site 

Fixes #314 

## Pages/Interfaces that will change
- /allies
-/businesses
-footer 
-/about

### Screenshots / video of changes

Screen Shot 2020-08-25 at 00 43 18
Screen Shot 2020-08-25 at 00 43 59

Drop some screenshots of the before and after of your work here. Better yet, take a screen recording using a tool like [Loom](https://www.loom.com/)
hovering on call-to-action links before the update : 
Screen Shot 2020-08-25 at 00 48 09
Screen Shot 2020-08-25 at 00 49 12

## Steps to test

1. Go to the /businesses or the allies page 
2. hover on any of the call-to-action links on each of the business or allies cards
3. you will observe the links changing to a purple color(which is defined by the new link styles standard)

### CODE REVIEW

**Comment by magnificode** [comment]
This looks great @AdrianTNare! We don't have any links within a dark background at the moment, could you drop in here how that darkBG variant would be applied? Just so we can have the history here for when we add a darker section!

**Comment by AdrianTNare** [comment]
For future references: call-to-action links on a dark background should have the following attribute-value pair : 
variant = "ctaBlackBg"

**Comment by racedale** [comment]
@all-contributors please add AdrianTNare for code

**Comment by racedale** [comment]
@all-contributors please add AdrianTNare for code

**Pull request merged**
