### PR TITLE
Feature: Added Cypress Test for Navigation Links and updated /businesses route to reflect final structure

### PR DESCRIPTION
**Pull request by dilloncoffman**
# Describe your PR
Added Cypress test for testing navigation links going to the correct routes.

Related to Trello task [Add cypress test for navigation](https://trello.com/c/f5qG2h07/32-add-cypress-test-for-navigation)

## Pages/Interfaces that will change
None

### Screenshots / video of changes
Test recording

## Steps to test

1. Run `npm run test:e2e` then click `navigation.test.js` in Cypress's test runner window.

### CODE REVIEW

**Comment by magnificode** [comment]
@dilloncoffman very much appreciate the PR here. These page slugs (and the navigation in all honestly) will be changing quite drastically once we get approved designs.

The data structure is getting finalized as well and will inform these decisions.

Are you cool to let this test sit in PR for a little while until I get that structure laid out? Or do you think it's best to drop this in as-is and update the tests as we finalize the structure?

**Comment by dilloncoffman** [comment]
@magnificode I'm totally cool to let this sit in PR until the structure is laid out. I'll be around in the Discord (Pansock) to help out with other tasks as they come in!

**Comment by magnificode** [comment]
Thank you! Once we get the structure updated I'll update you in this ticket.

**Comment by racedale** [comment]
- [ ] Update page slugs once finalized

**Comment by magnificode** [comment]
@dilloncoffman page slugs have been finalized!

Home (slug: "/")
About (slug: "/about")
Businesses (slug: "/businesses")
Allies (slug: "/allies")
Resources (slug: "/resources")

**Pull request merged**
